In [1]:
import pandas as pd

In [4]:
people = {
    'first': ['Corey', 'Jane', 'John'], 
    'last': ['Schafer', 'Doe', 'Doe'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [5]:
df = pd.DataFrame(people)

In [6]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [7]:
df['first'] + ' ' + df['last']

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: object

In [8]:
df['FullName'] = df['first'] + ' ' + df['last'] #we can use map also

In [9]:
df

   first     last                    email       FullName
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [11]:
df.drop(columns=['first','last'], inplace=True)

In [12]:
df

                     email       FullName
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [13]:
df['FullName'].str.split(' ')

0    [Corey, Schafer]
1         [Jane, Doe]
2         [John, Doe]
Name: FullName, dtype: object

In [14]:
df['FullName'].str.split(' ',expand = True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [16]:
df[['first', 'last']] = df['FullName'].str.split(' ',expand = True)

In [17]:
df

                     email       FullName  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [21]:
df.concat({'first' : 'tony'}, ignore_index = True)

AttributeError: 'DataFrame' object has no attribute 'concat'

In [22]:
import pandas as pd

# 1. Create a temporary DataFrame for your new row
new_row = pd.DataFrame([{'first': 'tony'}])

# 2. Use pd.concat() instead of df.concat()
df = pd.concat([df, new_row], ignore_index=True)

In [23]:
df

                     email       FullName  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   tony      NaN

In [24]:
people = {
    'first': ['tiney', 'steve'], 
    'last': ['stark', 'rogers'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com']
}

In [25]:
new_row = pd.DataFrame(people)

In [26]:
df = pd.concat([df, new_row], ignore_index=True)

In [27]:
df

                     email       FullName  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   tony      NaN
4  CoreyMSchafer@gmail.com            NaN  tiney    stark
5        JaneDoe@email.com            NaN  steve   rogers

In [28]:
 df.drop(index=4)

                     email       FullName  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   tony      NaN
5        JaneDoe@email.com            NaN  steve   rogers

In [31]:
filtrr2 = df['last']=='Doe'
df.drop(index=df[filtrr2].index)

                     email       FullName  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3                      NaN            NaN   tony      NaN
4  CoreyMSchafer@gmail.com            NaN  tiney    stark
5        JaneDoe@email.com            NaN  steve   rogers

In [ ]:
df